# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - replacements:
      darwin: macos
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: binary


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
